name: Bug
description: Report a bug
title: "[Bug]:"
labels: ["bug"]
projects: ["Telicent-io/36"]
body:
  - type: markdown
    attributes:
      value: |
        Report a bug!
  - type: textarea
    attributes:
      label: Description of defect
      description: What is the defect? If you know what caused it, add it here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce defect
      description: Describe how to reproduce the defect (or provide screenshots below)
      value: |
        1. Go to ...
        2. Click on ....
        3. Scroll down to ....
        4. See error 

        Environment (if appropriate)
        - Device: e.g iPhone 12
        - Browser: [e.g chrome, safari]
        - OS: [e.g iOS]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behaviour
      description: What is the 'right' behaviour? What does the outcome of a fix look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots? Anything that will give us more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
