name: Documentation
description: Create or update documentation (e.g README, Wiki, Guides, etc)
title: "[Documentation:] "
labels: ["documentation"]
projects: ["Telicent-io/36"]
body:
  - type: textarea
    attributes:
      label: Documentation to create/update
      description: Short summary of the documentation that should be added or updated (include links where appropriate)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: What does this documentation need to include in order to consider this ticket 'done'?
    validations:
      required: true
