name: Feature/Epic
description: A large body of work/Feature with linked implementation tasks
title: "[Feature/Epic]: "
projects: ["Telicent-io/36"]
body:
  - type: markdown
    attributes:
      value: |
        These tickets are not actionable tickets. Tasks should be raised in the 'Issues' section and linked to this issue-type (using task-list) when this feature is prioritised.
  - type: textarea
    attributes:
      label: Summary
      description: Provide a high level description of the suggested feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issues
      description: Break down the tasks to implement this epic/feature. You can add existing issues or convert these into issues later. 
      value: |
        - [ ] Task 1 
        - [ ] Task 2
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Is there a pain-point we're trying to solve with this feature? Expand here. Add any links of references if appropriate.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
