name: Feature
description: Epic-level theme/capability/feature to introduce 
title: "[Feature:] "
projects: ["Telicent-io/36"]
body:
- type: markdown
    attributes:
      value: |
       These tickets are not actionable tickets. Tasks should be raised and linked to this issue-type (using task-list) when this feature is prioritised.
  - type: textarea
    attributes:
      label: Summary
      Description: Provide a high level description of the suggested feature
    validations:
      required: true
- type: textarea
    attributes: 
      label: Additional information
      Description: Is there a pain-point we're trying to solve with this feature? Expand here. Add any links of references if appropriate.
Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false


